### ISSUE TITLE
Load Datasets error

### ISSUE THREAD

**Issue by bahingayi** [YuZhang-GitHub/1-Bit-ADCs#1]
u

**Comment by YuZhang-GitHub** [comment]
Hi, thank you very much for pointing out this problem and reaching out to me. Please use the link provided below for downloading the mat file.
https://drive.google.com/file/d/1CXwReLlqdbiAk3xVxNFEBAq0poaN6CE6/view?usp=sharing
If you still encounter a problem in using the file, please let me know.
Thanks.

**Comment by bahingayi** [comment]
Thank you for your response.
