### ISSUE TITLE
How to regenerate Figure 2 in this paper?

### ISSUE THREAD

**Issue by BassantTolba1234** [YuZhang-GitHub/1-Bit-ADCs#2]
Dear Sir,
Brilliant work ! Congratulations !
Please can you kindly share with me the code for regenerating Figure 2 in this paper please ..
I'm waiting for your reply.
Thanks in advance
Best regards,

**Comment by wang-777** [comment]
hi 

> Dear Sir,
> Brilliant work ! Congratulations !
> Please can you kindly share with me the code for regenerating Figure 2 in this paper please ..
> I'm waiting for your reply.
> Thanks in advance
> Best regards,

Have you got the answer, please?
How to regenerate Figure 2 in this paper?
I'm waiting for your reply.
Thanks in advance
Best regards,

**Comment by Cat-Guijun** [comment]
> hi
> 
> > Dear Sir,
> > Brilliant work ! Congratulations !
> > Please can you kindly share with me the code for regenerating Figure 2 in this paper please ..
> > I'm waiting for your reply.
> > Thanks in advance
> > Best regards,
> 
> Have you got the answer, please? How to regenerate Figure 2 in this paper? I'm waiting for your reply. Thanks in advance Best regards,

hi,
have you known  how  to regenerate the Fig.2?
Looking forward to your reply?
Thanks in advance.
Best regards.

**Comment by YuZhang-GitHub** [comment]
Hi, the training codes are identical to those used for generating Fig. 3. You simply calculate the NMSE on a per-channel basis with the testing dataset.

**Comment by Cat-Guijun** [comment]
> Hi, the training codes are identical to those used for generating Fig. 3. You simply calculate the NMSE on a per-channel basis with the testing dataset.

Dear sir,
Thanks to your reply and your brilliant work!
Best regards to you, thanks!
